name: kitahack_budget_gang
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_localizations: # 👈 Required
    sdk: flutter
  intl: 0.19.0
  # Keep camera version 0.10.5+5
  camera: ^0.10.5+5
  # (flutter pub add animate_do) run this in terminal to install animation

  image: ^4.0.17
  # Upgrade tflite_flutter to a newer version (e.g., 0.10.0)
  tflite_flutter: ^0.11.0

  # Other dependencies
  path_provider: ^2.0.15
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  animate_do: ^4.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  generate: true # 👈 Enables Flutter localization generation
  uses-material-design: true
  assets:
    - assets/best_float16.tflite
    - assets/best_float32.tflite
    - assets/hand1_5_bot_seg_1_cropped.jpeg
    - assets/labels.txt
    - assets/wong.png
    - assets/gan.png
    - assets/tan.png
    - assets/yap.png
    - assets/ASL_Alphabet.jpg
